### ISSUE TITLE
Can edit in preview using drag&drop selection

### ISSUE THREAD

**Issue by grissius** [grissius/markup-editor#10]
Content editable feature. Preview should be RO.

**Comment by jirutka** [comment]
Huh, how did you manage to make editable preview? :)

**Comment by grissius** [comment]
Sorry, since I am the only one working on the project at the moment, I sometimes create issues as todos for myself with very little explanation.

**The preview is not editable in user interaction meaning, and should not be.**

However, at this moment the preview has [`contenteditable`](https://www.w3schools.com/tags/att_global_contenteditable.asp) and blocked onChange, so it simulates RO, but drag&drop selection does not fire the event.

...then  why on earth does it have the`contenteditable` attribute at the first place? From UI perspective the editor should minimalize needs to use mouse in interaction. You can catch shortcut events when focused on editor, but since the editor has pure preview mode, you would lose focus while in it. Thus early stage fix was to make preview focusable and give it focus when source code is hidden.

**But could it be?**
It could if given LML can be easily partially rendered. This is the case for markdown, but not so much for adoc. It is not priority for now. But [Typora](https://typora.io/) handles this masterfully in my expirience.

**Comment by jirutka** [comment]
That's okay, I was just curious. :) Real editable preview is quite complicated feature, not something that happens by accident. :) Thanks for the explanation.

**Comment by grissius** [comment]
#47
