### ISSUE TITLE
Tables and images in preview can be resized – bug, or feature?

### ISSUE THREAD

**Issue by jirutka** [grissius/markup-editor#29]
![Screencast demonstrating the issue](https://user-images.githubusercontent.com/949228/33340735-da9ef482-d474-11e7-8d5c-fc48579a4cdf.gif)

This is caused by attribute `_moz_resizing="true"` on element `<table>`. Changing it to `false` disables this ability.

**Browser:** Firefox 55.0.3 on macOS

**Comment by grissius** [comment]
It's a bug. Almost certainly related to #10 

Thanks for reporting!

**Comment by grissius** [comment]
#47

**Comment by grissius** [comment]
#47
