### ISSUE TITLE
Links inside preview are not “clickable”

### ISSUE THREAD

**Issue by jirutka** [grissius/markup-editor#30]
Links are rendered correctly as `<a>` tag, but its default action for left left click is blocked. User can open the link from browser’s context menu, but not by clicking or tapping on it.

**Comment by jirutka** [comment]
I suggest to inject attribute `target="_blank"` to all links inside preview, except anchors, so user will not accidentally leave the editor.

**Comment by grissius** [comment]
Bug is definitely here related to #10. Blank target agreed.

**Comment by grissius** [comment]
#47
