### ISSUE TITLE
Spellcheck control

### ISSUE THREAD

**Issue by grissius** [grissius/markup-editor#31]
Add statusbar for spellcheck (choose language or disable)

**Comment by jirutka** [comment]
Why? Browsers already provide spellcheck.

![Spellcheck in browser](https://user-images.githubusercontent.com/949228/33342772-2274620a-d47b-11e7-90bc-254766820af9.png)

**Comment by grissius** [comment]
Are you sure the waves in screenshot are due to browser spellcheck and not due to already implemented spellcheck feature? (master has english spellcheck with underline red wavy)

Application spellcheck can be controlled (though at this time it is not) and can detect and ignore code blocks and keywords.

**Comment by jirutka** [comment]
Aha, I’m not, I didn’t know that spellcheck is already implemented. However, I’m still not sure if it’s a good idea to implement a spellcheck into the editor. It’s quite complex feature.

**Comment by grissius** [comment]
Giving it a second thought, maybe you're right. Did not think it was much of a deal, but it does seem to be :thinking: 

Maybe it's not worth the hassle. I am considering removal of the existing feature.

**Comment by grissius** [comment]
Closing for now due to #44
